packages:
    - "packages/cli"
    - "packages/gnim"
    - "packages/gtk4"
    - "packages/gtk3"
    - "packages/gnome-shell"
    - "packages/create"
    - "packages/io"

catalog:
    "@types/node": ^26.1.2
    "@eslint/js": ^10.0.1
    eslint: ^10.7.0
    typescript: ^6.0.0
    typescript-eslint: ^8.64.0

allowBuilds:
    esbuild: false
