name: Lint

on:
    push:
        branches:
            - "**"

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 10

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            # TODO: get .gir files from a faster source, no need to pull everything
            - name: Install Gtk deps
              run: |
                  sudo apt update -y
                  sudo apt install -y libgtk-4-dev

            - name: Generate types
              run: |
                  ./node_modules/@gnim-js/linux-x64/gnim types -d /usr/share/gir-1.0

            - name: Lint
              run: pnpm lint
